services:
  clash:
    image: dreamacro/clash-premium
    container_name: clash
    hostname: clash
    restart: unless-stopped
    ports:
      - 7890:7890
      - 7891:7891
      - 19091:9090
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    environment:
      - TZ=Asia/Shanghai

  yacd:
    image: ghcr.io/haishanh/yacd:master
    container_name: yacd
    hostname: yacd
    restart: unless-stopped
    ports:
      - 20242:80
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - clash
